// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package eventsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :one
SELECT global_position, event_id, aggregate_type, aggregate_id, owner_user_id, aggregate_version, event_type, schema_version, payload, metadata, actor_user_id, command_id, command_event_index, occurred_at, recorded_at
FROM app_api.append_event(
    $1::UUID,
    $2::TEXT,
    $3::UUID,
    $4::UUID,
    $5::BIGINT,
    $6::TEXT,
    $7::INTEGER,
    $8::JSONB,
    $9::JSONB,
    $10::UUID,
    $11::UUID,
    $12::SMALLINT,
    $13::TIMESTAMPTZ
)
`

type AppendEventParams struct {
	EventID                  uuid.UUID          `json:"event_id"`
	AggregateType            string             `json:"aggregate_type"`
	AggregateID              uuid.UUID          `json:"aggregate_id"`
	OwnerUserID              uuid.UUID          `json:"owner_user_id"`
	ExpectedAggregateVersion int64              `json:"expected_aggregate_version"`
	EventType                string             `json:"event_type"`
	SchemaVersion            int32              `json:"schema_version"`
	Payload                  []byte             `json:"payload"`
	Metadata                 []byte             `json:"metadata"`
	ActorUserID              pgtype.UUID        `json:"actor_user_id"`
	CommandID                uuid.UUID          `json:"command_id"`
	CommandEventIndex        int16              `json:"command_event_index"`
	OccurredAt               pgtype.Timestamptz `json:"occurred_at"`
}

// owner_user_id identifies the user from the authenticated request context.
func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (EventStore, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.EventID,
		arg.AggregateType,
		arg.AggregateID,
		arg.OwnerUserID,
		arg.ExpectedAggregateVersion,
		arg.EventType,
		arg.SchemaVersion,
		arg.Payload,
		arg.Metadata,
		arg.ActorUserID,
		arg.CommandID,
		arg.CommandEventIndex,
		arg.OccurredAt,
	)
	var i EventStore
	err := row.Scan(
		&i.GlobalPosition,
		&i.EventID,
		&i.AggregateType,
		&i.AggregateID,
		&i.OwnerUserID,
		&i.AggregateVersion,
		&i.EventType,
		&i.SchemaVersion,
		&i.Payload,
		&i.Metadata,
		&i.ActorUserID,
		&i.CommandID,
		&i.CommandEventIndex,
		&i.OccurredAt,
		&i.RecordedAt,
	)
	return i, err
}

const getAggregateVersion = `-- name: GetAggregateVersion :one
SELECT app_api.get_aggregate_version(
    $1::UUID,
    $2::TEXT,
    $3::UUID
) AS version
`

type GetAggregateVersionParams struct {
	OwnerUserID   uuid.UUID `json:"owner_user_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
}

func (q *Queries) GetAggregateVersion(ctx context.Context, arg GetAggregateVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAggregateVersion, arg.OwnerUserID, arg.AggregateType, arg.AggregateID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT global_position, event_id, aggregate_type, aggregate_id, owner_user_id, aggregate_version, event_type, schema_version, payload, metadata, actor_user_id, command_id, command_event_index, occurred_at, recorded_at
FROM app_api.get_event_by_id(
    $1::UUID,
    $2::UUID
)
`

type GetEventByIDParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	EventID     uuid.UUID `json:"event_id"`
}

// owner_user_id limits the lookup to the authenticated user.
func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (EventStore, error) {
	row := q.db.QueryRow(ctx, getEventByID, arg.OwnerUserID, arg.EventID)
	var i EventStore
	err := row.Scan(
		&i.GlobalPosition,
		&i.EventID,
		&i.AggregateType,
		&i.AggregateID,
		&i.OwnerUserID,
		&i.AggregateVersion,
		&i.EventType,
		&i.SchemaVersion,
		&i.Payload,
		&i.Metadata,
		&i.ActorUserID,
		&i.CommandID,
		&i.CommandEventIndex,
		&i.OccurredAt,
		&i.RecordedAt,
	)
	return i, err
}

const getEventStoreBoundary = `-- name: GetEventStoreBoundary :one
SELECT
    last_position AS high_water,
    (EXTRACT(EPOCH FROM statement_timestamp()) * 1000000)::BIGINT AS captured_at_unix_micro
FROM event_store_position
WHERE singleton = TRUE
`

type GetEventStoreBoundaryRow struct {
	HighWater           int64 `json:"high_water"`
	CapturedAtUnixMicro int64 `json:"captured_at_unix_micro"`
}

func (q *Queries) GetEventStoreBoundary(ctx context.Context) (GetEventStoreBoundaryRow, error) {
	row := q.db.QueryRow(ctx, getEventStoreBoundary)
	var i GetEventStoreBoundaryRow
	err := row.Scan(&i.HighWater, &i.CapturedAtUnixMicro)
	return i, err
}

const listAggregateEvents = `-- name: ListAggregateEvents :many
SELECT global_position, event_id, aggregate_type, aggregate_id, owner_user_id, aggregate_version, event_type, schema_version, payload, metadata, actor_user_id, command_id, command_event_index, occurred_at, recorded_at
FROM app_api.list_aggregate_events(
    $1::UUID,
    $2::TEXT,
    $3::UUID,
    $4::BIGINT,
    $5::INTEGER
)
`

type ListAggregateEventsParams struct {
	OwnerUserID   uuid.UUID `json:"owner_user_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	AfterVersion  int64     `json:"after_version"`
	PageSize      int32     `json:"page_size"`
}

func (q *Queries) ListAggregateEvents(ctx context.Context, arg ListAggregateEventsParams) ([]EventStore, error) {
	rows, err := q.db.Query(ctx, listAggregateEvents,
		arg.OwnerUserID,
		arg.AggregateType,
		arg.AggregateID,
		arg.AfterVersion,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventStore{}
	for rows.Next() {
		var i EventStore
		if err := rows.Scan(
			&i.GlobalPosition,
			&i.EventID,
			&i.AggregateType,
			&i.AggregateID,
			&i.OwnerUserID,
			&i.AggregateVersion,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
			&i.Metadata,
			&i.ActorUserID,
			&i.CommandID,
			&i.CommandEventIndex,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfterPosition = `-- name: ListEventsAfterPosition :many
SELECT global_position, event_id, aggregate_type, aggregate_id, owner_user_id, aggregate_version, event_type, schema_version, payload, metadata, actor_user_id, command_id, command_event_index, occurred_at, recorded_at
FROM event_store
WHERE global_position > $1
ORDER BY global_position ASC
LIMIT LEAST(GREATEST($2::INTEGER, 1), 500)
`

type ListEventsAfterPositionParams struct {
	AfterPosition int64 `json:"after_position"`
	PageSize      int32 `json:"page_size"`
}

// Projection workers consume events in global order when updating read models.
func (q *Queries) ListEventsAfterPosition(ctx context.Context, arg ListEventsAfterPositionParams) ([]EventStore, error) {
	rows, err := q.db.Query(ctx, listEventsAfterPosition, arg.AfterPosition, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventStore{}
	for rows.Next() {
		var i EventStore
		if err := rows.Scan(
			&i.GlobalPosition,
			&i.EventID,
			&i.AggregateType,
			&i.AggregateID,
			&i.OwnerUserID,
			&i.AggregateVersion,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
			&i.Metadata,
			&i.ActorUserID,
			&i.CommandID,
			&i.CommandEventIndex,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByCommandID = `-- name: ListEventsByCommandID :many
SELECT global_position, event_id, aggregate_type, aggregate_id, owner_user_id, aggregate_version, event_type, schema_version, payload, metadata, actor_user_id, command_id, command_event_index, occurred_at, recorded_at
FROM app_api.list_events_by_command_id(
    $1::UUID,
    $2::UUID
)
`

type ListEventsByCommandIDParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	CommandID   uuid.UUID `json:"command_id"`
}

func (q *Queries) ListEventsByCommandID(ctx context.Context, arg ListEventsByCommandIDParams) ([]EventStore, error) {
	rows, err := q.db.Query(ctx, listEventsByCommandID, arg.OwnerUserID, arg.CommandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventStore{}
	for rows.Next() {
		var i EventStore
		if err := rows.Scan(
			&i.GlobalPosition,
			&i.EventID,
			&i.AggregateType,
			&i.AggregateID,
			&i.OwnerUserID,
			&i.AggregateVersion,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
			&i.Metadata,
			&i.ActorUserID,
			&i.CommandID,
			&i.CommandEventIndex,
			&i.OccurredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEventsByPosition = `-- name: ListUserEventsByPosition :many
SELECT global_position, event_id, owner_user_id, event_type, schema_version, payload
FROM app_api.list_daily_summary_events_by_position(
    $1::UUID,
    $2::BIGINT,
    $3::BIGINT,
    $4::INTEGER
)
`

type ListUserEventsByPositionParams struct {
	OwnerUserID   uuid.UUID `json:"owner_user_id"`
	AfterPosition int64     `json:"after_position"`
	ToPosition    int64     `json:"to_position"`
	PageSize      int32     `json:"page_size"`
}

func (q *Queries) ListUserEventsByPosition(ctx context.Context, arg ListUserEventsByPositionParams) ([]DailySummaryEventView, error) {
	rows, err := q.db.Query(ctx, listUserEventsByPosition,
		arg.OwnerUserID,
		arg.AfterPosition,
		arg.ToPosition,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySummaryEventView{}
	for rows.Next() {
		var i DailySummaryEventView
		if err := rows.Scan(
			&i.GlobalPosition,
			&i.EventID,
			&i.OwnerUserID,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventCommand = `-- name: LockEventCommand :exec
SELECT app_api.lock_event_command(
    $1::UUID,
    $2::UUID
)
`

type LockEventCommandParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	CommandID   uuid.UUID `json:"command_id"`
}

func (q *Queries) LockEventCommand(ctx context.Context, arg LockEventCommandParams) error {
	_, err := q.db.Exec(ctx, lockEventCommand, arg.OwnerUserID, arg.CommandID)
	return err
}
