// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AggregateStream struct {
	AggregateType  string    `json:"aggregate_type"`
	AggregateID    uuid.UUID `json:"aggregate_id"`
	OwnerUserID    uuid.UUID `json:"owner_user_id"`
	CurrentVersion int64     `json:"current_version"`
}

type EventStore struct {
	GlobalPosition    int64              `json:"global_position"`
	EventID           uuid.UUID          `json:"event_id"`
	AggregateType     string             `json:"aggregate_type"`
	AggregateID       uuid.UUID          `json:"aggregate_id"`
	OwnerUserID       uuid.UUID          `json:"owner_user_id"`
	AggregateVersion  int64              `json:"aggregate_version"`
	EventType         string             `json:"event_type"`
	SchemaVersion     int32              `json:"schema_version"`
	Payload           []byte             `json:"payload"`
	Metadata          []byte             `json:"metadata"`
	ActorUserID       pgtype.UUID        `json:"actor_user_id"`
	CommandID         uuid.UUID          `json:"command_id"`
	CommandEventIndex int16              `json:"command_event_index"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	RecordedAt        pgtype.Timestamptz `json:"recorded_at"`
}

type EventStorePosition struct {
	Singleton    bool  `json:"singleton"`
	LastPosition int64 `json:"last_position"`
}

type ProjectionCheckpoint struct {
	ProjectionName string             `json:"projection_name"`
	LastPosition   int64              `json:"last_position"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RefreshSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
