// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projection_checkpoints.sql

package eventsqlc

import (
	"context"
)

const getProjectionCheckpoint = `-- name: GetProjectionCheckpoint :one
SELECT COALESCE((
    SELECT last_position
    FROM projection_checkpoints
    WHERE projection_name = $1
), 0)::BIGINT AS last_position
`

// Returns the last event position processed by a projection.
func (q *Queries) GetProjectionCheckpoint(ctx context.Context, projectionName string) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectionCheckpoint, projectionName)
	var last_position int64
	err := row.Scan(&last_position)
	return last_position, err
}

const saveProjectionCheckpoint = `-- name: SaveProjectionCheckpoint :exec
SELECT app_api.save_projection_checkpoint(
    $1::TEXT,
    $2::BIGINT
)
`

type SaveProjectionCheckpointParams struct {
	ProjectionName string `json:"projection_name"`
	LastPosition   int64  `json:"last_position"`
}

// Advances a projection checkpoint after its read model is updated.
func (q *Queries) SaveProjectionCheckpoint(ctx context.Context, arg SaveProjectionCheckpointParams) error {
	_, err := q.db.Exec(ctx, saveProjectionCheckpoint, arg.ProjectionName, arg.LastPosition)
	return err
}
