run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - unconvert

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
