// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_summary.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDailySummaryCheckpointForUpdate = `-- name: GetDailySummaryCheckpointForUpdate :one
SELECT user_id, last_check_in_at, last_event_position
FROM daily_summary_checkpoints
WHERE user_id = $1
FOR UPDATE
`

type GetDailySummaryCheckpointForUpdateRow struct {
	UserID            uuid.UUID
	LastCheckInAt     pgtype.Timestamptz
	LastEventPosition int64
}

func (q *Queries) GetDailySummaryCheckpointForUpdate(ctx context.Context, userID uuid.UUID) (GetDailySummaryCheckpointForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getDailySummaryCheckpointForUpdate, userID)
	var i GetDailySummaryCheckpointForUpdateRow
	err := row.Scan(&i.UserID, &i.LastCheckInAt, &i.LastEventPosition)
	return i, err
}

const insertDailySummaryCheckpoint = `-- name: InsertDailySummaryCheckpoint :execrows
INSERT INTO daily_summary_checkpoints (
    user_id,
    last_check_in_at,
    last_event_position
)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
`

type InsertDailySummaryCheckpointParams struct {
	UserID            uuid.UUID
	LastCheckInAt     pgtype.Timestamptz
	LastEventPosition int64
}

func (q *Queries) InsertDailySummaryCheckpoint(ctx context.Context, arg InsertDailySummaryCheckpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDailySummaryCheckpoint, arg.UserID, arg.LastCheckInAt, arg.LastEventPosition)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDailySummaryEventFailure = `-- name: RecordDailySummaryEventFailure :one
SELECT app_api.record_daily_summary_event_failure(
    $1::UUID,
    $2::UUID,
    $3::BIGINT,
    $4::TEXT,
    $5::INTEGER,
    $6::TEXT
)
`

type RecordDailySummaryEventFailureParams struct {
	UserID         uuid.UUID
	EventID        uuid.UUID
	GlobalPosition int64
	EventType      string
	SchemaVersion  int32
	Reason         string
}

func (q *Queries) RecordDailySummaryEventFailure(ctx context.Context, arg RecordDailySummaryEventFailureParams) (bool, error) {
	row := q.db.QueryRow(ctx, recordDailySummaryEventFailure,
		arg.UserID,
		arg.EventID,
		arg.GlobalPosition,
		arg.EventType,
		arg.SchemaVersion,
		arg.Reason,
	)
	var record_daily_summary_event_failure bool
	err := row.Scan(&record_daily_summary_event_failure)
	return record_daily_summary_event_failure, err
}

const updateDailySummaryCheckpoint = `-- name: UpdateDailySummaryCheckpoint :execrows
UPDATE daily_summary_checkpoints
SET last_check_in_at = $2,
    last_event_position = $3,
    updated_at = now()
WHERE user_id = $1
`

type UpdateDailySummaryCheckpointParams struct {
	UserID            uuid.UUID
	LastCheckInAt     pgtype.Timestamptz
	LastEventPosition int64
}

func (q *Queries) UpdateDailySummaryCheckpoint(ctx context.Context, arg UpdateDailySummaryCheckpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDailySummaryCheckpoint, arg.UserID, arg.LastCheckInAt, arg.LastEventPosition)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
