// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const advanceLeaderboardPetLevel = `-- name: AdvanceLeaderboardPetLevel :execrows
UPDATE leaderboard_pet_levels
SET level = $3,
    level_reached_position = $4,
    updated_at = now()
WHERE user_id = $1
  AND pet_id = $2
  AND level < $3
  AND level_reached_position < $4
`

type AdvanceLeaderboardPetLevelParams struct {
	UserID               uuid.UUID
	PetID                uuid.UUID
	Level                int32
	LevelReachedPosition int64
}

func (q *Queries) AdvanceLeaderboardPetLevel(ctx context.Context, arg AdvanceLeaderboardPetLevelParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceLeaderboardPetLevel,
		arg.UserID,
		arg.PetID,
		arg.Level,
		arg.LevelReachedPosition,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserLeaderboardPositions = `-- name: GetUserLeaderboardPositions :one
WITH pet_ranked AS (
    SELECT
        ROW_NUMBER() OVER (
            ORDER BY pet.level DESC, pet.level_reached_position ASC, pet.user_id ASC
        ) AS rank,
        pet.user_id
    FROM leaderboard_pet_levels AS pet
    JOIN users ON users.id = pet.user_id
    WHERE users.status = 'active'
),
game_ranked AS (
    SELECT
        ROW_NUMBER() OVER (
            ORDER BY game.best_score DESC, game.achieved_position ASC, game.user_id ASC
        ) AS rank,
        game.user_id
    FROM leaderboard_game_scores AS game
    JOIN users ON users.id = game.user_id
    WHERE users.status = 'active'
)
SELECT
    COALESCE((
        SELECT rank FROM pet_ranked WHERE user_id = $1::UUID
    ), 0)::BIGINT AS pet_level_rank,
    COALESCE((
        SELECT rank FROM game_ranked WHERE user_id = $1::UUID
    ), 0)::BIGINT AS game_score_rank
`

type GetUserLeaderboardPositionsRow struct {
	PetLevelRank  int64
	GameScoreRank int64
}

func (q *Queries) GetUserLeaderboardPositions(ctx context.Context, userID uuid.UUID) (GetUserLeaderboardPositionsRow, error) {
	row := q.db.QueryRow(ctx, getUserLeaderboardPositions, userID)
	var i GetUserLeaderboardPositionsRow
	err := row.Scan(&i.PetLevelRank, &i.GameScoreRank)
	return i, err
}

const insertLeaderboardPet = `-- name: InsertLeaderboardPet :execrows
INSERT INTO leaderboard_pet_levels (
    user_id,
    pet_id,
    pet_name,
    species,
    level,
    level_reached_position
)
VALUES ($1, $2, $3, $4, 1, $5)
ON CONFLICT (user_id) DO NOTHING
`

type InsertLeaderboardPetParams struct {
	UserID               uuid.UUID
	PetID                uuid.UUID
	PetName              string
	Species              string
	LevelReachedPosition int64
}

func (q *Queries) InsertLeaderboardPet(ctx context.Context, arg InsertLeaderboardPetParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLeaderboardPet,
		arg.UserID,
		arg.PetID,
		arg.PetName,
		arg.Species,
		arg.LevelReachedPosition,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listGameScoreLeaderboard = `-- name: ListGameScoreLeaderboard :many
WITH ranked AS (
    SELECT
        ROW_NUMBER() OVER (
            ORDER BY game.best_score DESC, game.achieved_position ASC, game.user_id ASC
        ) AS rank,
        game.user_id,
        users.display_name,
        game.best_score
    FROM leaderboard_game_scores AS game
    JOIN users ON users.id = game.user_id
    WHERE users.status = 'active'
)
SELECT rank, user_id, display_name, best_score
FROM ranked
ORDER BY rank ASC
LIMIT LEAST(GREATEST($2::INTEGER, 1), 100)
OFFSET GREATEST($1::INTEGER, 0)
`

type ListGameScoreLeaderboardParams struct {
	PageOffset int32
	PageSize   int32
}

type ListGameScoreLeaderboardRow struct {
	Rank        int64
	UserID      uuid.UUID
	DisplayName string
	BestScore   int64
}

func (q *Queries) ListGameScoreLeaderboard(ctx context.Context, arg ListGameScoreLeaderboardParams) ([]ListGameScoreLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, listGameScoreLeaderboard, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameScoreLeaderboardRow{}
	for rows.Next() {
		var i ListGameScoreLeaderboardRow
		if err := rows.Scan(
			&i.Rank,
			&i.UserID,
			&i.DisplayName,
			&i.BestScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPetLevelLeaderboard = `-- name: ListPetLevelLeaderboard :many
WITH ranked AS (
    SELECT
        ROW_NUMBER() OVER (
            ORDER BY pet.level DESC, pet.level_reached_position ASC, pet.user_id ASC
        ) AS rank,
        pet.user_id,
        users.display_name,
        pet.pet_id,
        pet.pet_name,
        pet.species,
        pet.level
    FROM leaderboard_pet_levels AS pet
    JOIN users ON users.id = pet.user_id
    WHERE users.status = 'active'
)
SELECT rank, user_id, display_name, pet_id, pet_name, species, level
FROM ranked
ORDER BY rank ASC
LIMIT LEAST(GREATEST($2::INTEGER, 1), 100)
OFFSET GREATEST($1::INTEGER, 0)
`

type ListPetLevelLeaderboardParams struct {
	PageOffset int32
	PageSize   int32
}

type ListPetLevelLeaderboardRow struct {
	Rank        int64
	UserID      uuid.UUID
	DisplayName string
	PetID       uuid.UUID
	PetName     string
	Species     string
	Level       int32
}

func (q *Queries) ListPetLevelLeaderboard(ctx context.Context, arg ListPetLevelLeaderboardParams) ([]ListPetLevelLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, listPetLevelLeaderboard, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPetLevelLeaderboardRow{}
	for rows.Next() {
		var i ListPetLevelLeaderboardRow
		if err := rows.Scan(
			&i.Rank,
			&i.UserID,
			&i.DisplayName,
			&i.PetID,
			&i.PetName,
			&i.Species,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLeaderboardEventFailure = `-- name: RecordLeaderboardEventFailure :execrows
INSERT INTO leaderboard_event_failures (
    event_id,
    user_id,
    global_position,
    event_type,
    schema_version,
    reason
)
SELECT
    stored.event_id,
    stored.owner_user_id,
    stored.global_position,
    stored.event_type,
    stored.schema_version,
    $1::TEXT
FROM event_store AS stored
WHERE stored.event_id = $2::UUID
  AND stored.owner_user_id = $3::UUID
  AND stored.global_position = $4::BIGINT
  AND stored.event_type = $5::TEXT
  AND stored.schema_version = $6::INTEGER
ON CONFLICT (event_id) DO UPDATE
SET reason = EXCLUDED.reason,
    detected_at = now()
WHERE leaderboard_event_failures.user_id = EXCLUDED.user_id
  AND leaderboard_event_failures.global_position = EXCLUDED.global_position
  AND leaderboard_event_failures.event_type = EXCLUDED.event_type
  AND leaderboard_event_failures.schema_version = EXCLUDED.schema_version
`

type RecordLeaderboardEventFailureParams struct {
	Reason         string
	EventID        uuid.UUID
	UserID         uuid.UUID
	GlobalPosition int64
	EventType      string
	SchemaVersion  int32
}

func (q *Queries) RecordLeaderboardEventFailure(ctx context.Context, arg RecordLeaderboardEventFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordLeaderboardEventFailure,
		arg.Reason,
		arg.EventID,
		arg.UserID,
		arg.GlobalPosition,
		arg.EventType,
		arg.SchemaVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertLeaderboardGameScore = `-- name: UpsertLeaderboardGameScore :execrows
INSERT INTO leaderboard_game_scores (
    user_id,
    session_id,
    best_score,
    achieved_position
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET session_id = EXCLUDED.session_id,
    best_score = EXCLUDED.best_score,
    achieved_position = EXCLUDED.achieved_position,
    updated_at = now()
WHERE leaderboard_game_scores.best_score < EXCLUDED.best_score
`

type UpsertLeaderboardGameScoreParams struct {
	UserID           uuid.UUID
	SessionID        uuid.UUID
	BestScore        int64
	AchievedPosition int64
}

func (q *Queries) UpsertLeaderboardGameScore(ctx context.Context, arg UpsertLeaderboardGameScoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertLeaderboardGameScore,
		arg.UserID,
		arg.SessionID,
		arg.BestScore,
		arg.AchievedPosition,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
