// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimTaskProgress(ctx context.Context, arg ClaimTaskProgressParams) (uuid.UUID, error)
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserReward(ctx context.Context, arg CreateUserRewardParams) (UserReward, error)
	DeleteRefreshSession(ctx context.Context, tokenHash []byte) (int64, error)
	GetDailyRewardProgress(ctx context.Context, userID uuid.UUID) (GetDailyRewardProgressRow, error)
	GetRefreshSessionByTokenHash(ctx context.Context, tokenHash []byte) (RefreshSession, error)
	GetRewardDefinitionByCode(ctx context.Context, code string) (RewardDefinition, error)
	GetRewardForDay(ctx context.Context, dayNumber int32) (RewardDefinition, error)
	GetTaskWithProgressByCode(ctx context.Context, arg GetTaskWithProgressByCodeParams) (GetTaskWithProgressByCodeRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListTasksWithProgress(ctx context.Context, userID uuid.UUID) ([]ListTasksWithProgressRow, error)
	ListUserRewards(ctx context.Context, userID uuid.UUID) ([]UserReward, error)
	LogDailyRewardClaim(ctx context.Context, arg LogDailyRewardClaimParams) error
	UpsertDailyRewardProgress(ctx context.Context, arg UpsertDailyRewardProgressParams) error
}

var _ Querier = (*Queries)(nil)
