// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimTaskProgress = `-- name: ClaimTaskProgress :one
UPDATE user_task_progress
SET status = 'claimed', claimed_at = now()
WHERE user_id = $1 AND task_definition_id = $2 AND status = 'completed'
RETURNING id
`

type ClaimTaskProgressParams struct {
	UserID           uuid.UUID
	TaskDefinitionID uuid.UUID
}

func (q *Queries) ClaimTaskProgress(ctx context.Context, arg ClaimTaskProgressParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimTaskProgress, arg.UserID, arg.TaskDefinitionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTaskWithProgressByCode = `-- name: GetTaskWithProgressByCode :one
SELECT
    td.id, td.code, td.type, td.title, td.description, td.target_metric, td.target_value,
    td.reward_definition_id,
    rd.code AS reward_code, rd.title AS reward_title, rd.description AS reward_description,
    utp.current_value, utp.status, utp.completed_at, utp.claimed_at
FROM task_definitions td
JOIN reward_definitions rd ON rd.id = td.reward_definition_id
LEFT JOIN user_task_progress utp ON utp.task_definition_id = td.id AND utp.user_id = $1
WHERE td.code = $2 AND td.is_active = true
`

type GetTaskWithProgressByCodeParams struct {
	UserID uuid.UUID
	Code   string
}

type GetTaskWithProgressByCodeRow struct {
	ID                 uuid.UUID
	Code               string
	Type               string
	Title              string
	Description        string
	TargetMetric       string
	TargetValue        int32
	RewardDefinitionID uuid.UUID
	RewardCode         string
	RewardTitle        string
	RewardDescription  string
	CurrentValue       pgtype.Int4
	Status             pgtype.Text
	CompletedAt        pgtype.Timestamptz
	ClaimedAt          pgtype.Timestamptz
}

func (q *Queries) GetTaskWithProgressByCode(ctx context.Context, arg GetTaskWithProgressByCodeParams) (GetTaskWithProgressByCodeRow, error) {
	row := q.db.QueryRow(ctx, getTaskWithProgressByCode, arg.UserID, arg.Code)
	var i GetTaskWithProgressByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.TargetMetric,
		&i.TargetValue,
		&i.RewardDefinitionID,
		&i.RewardCode,
		&i.RewardTitle,
		&i.RewardDescription,
		&i.CurrentValue,
		&i.Status,
		&i.CompletedAt,
		&i.ClaimedAt,
	)
	return i, err
}

const listTasksWithProgress = `-- name: ListTasksWithProgress :many
SELECT
    td.id, td.code, td.type, td.title, td.description, td.target_metric, td.target_value,
    td.reward_definition_id,
    rd.code AS reward_code, rd.title AS reward_title, rd.description AS reward_description,
    utp.current_value, utp.status, utp.completed_at, utp.claimed_at
FROM task_definitions td
JOIN reward_definitions rd ON rd.id = td.reward_definition_id
LEFT JOIN user_task_progress utp ON utp.task_definition_id = td.id AND utp.user_id = $1
WHERE td.is_active = true
ORDER BY td.type, td.code
`

type ListTasksWithProgressRow struct {
	ID                 uuid.UUID
	Code               string
	Type               string
	Title              string
	Description        string
	TargetMetric       string
	TargetValue        int32
	RewardDefinitionID uuid.UUID
	RewardCode         string
	RewardTitle        string
	RewardDescription  string
	CurrentValue       pgtype.Int4
	Status             pgtype.Text
	CompletedAt        pgtype.Timestamptz
	ClaimedAt          pgtype.Timestamptz
}

func (q *Queries) ListTasksWithProgress(ctx context.Context, userID uuid.UUID) ([]ListTasksWithProgressRow, error) {
	rows, err := q.db.Query(ctx, listTasksWithProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksWithProgressRow{}
	for rows.Next() {
		var i ListTasksWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.TargetMetric,
			&i.TargetValue,
			&i.RewardDefinitionID,
			&i.RewardCode,
			&i.RewardTitle,
			&i.RewardDescription,
			&i.CurrentValue,
			&i.Status,
			&i.CompletedAt,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
